setlocal

@echo off

set "SOURCE_DIR=%CD%"
set "INSTALL_DIR=%CD%"
set "BUILD_DIR=%CD%\build"

set VMIME_CONFIG=

set "VMIME_CONFIG=%VMIME_CONFIG% -DCMAKE_INSTALL_LIBDIR:PATH=lib\32\Win\
set "VMIME_CONFIG=%VMIME_CONFIG% -DCMAKE_INSTALL_PREFIX:PATH=%INSTALL_DIR%"

rem static or shared
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_BUILD_STATIC_LIBRARY:BOOL=ON"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_BUILD_SHARED_LIBRARY:BOOL=OFF"

rem turn off messaging
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_MESSAGING_FEATURES:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_MESSAGING_PROTO_SENDMAIL:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_MESSAGING_PROTO_IMAP:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_MESSAGING_PROTO_SMTP:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_MESSAGING_PROTO_MAILDIR:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_MESSAGING_PROTO_POP3:BOOL=OFF"
rem turn off encryption (used for messaging?)
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_SASL_SUPPORT:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_SASL_SUPPORT:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_HAVE_TLS_SUPPORT:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_TLS_SUPPORT_LIB_IS_GNUTLS:BOOL=OFF"

rem use iconv (ice support is limited in vmime)
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_CHARSETCONV_LIB_IS_ICU:BOOL=OFF"
set "VMIME_CONFIG=%VMIME_CONFIG% -DVMIME_CHARSETCONV_LIB_IS_ICONV:BOOL=ON"

set "VMIME_CONFIG=%VMIME_CONFIG% -DICONV_LIBRARIES:FILEPATH=%SOURCE_DIR%/../libiconv/lib/32/Win/libiconv.lib"
set "VMIME_CONFIG=%VMIME_CONFIG% -DICONV_INCLUDE_DIR:PATH=%SOURCE_DIR%/../libiconv/include"

rem set "VMIME_CONFIG=%VMIME_CONFIG% -DCMAKE_BUILD_TYPE=Debug
set "VMIME_CONFIG=%VMIME_CONFIG% -DCMAKE_BUILD_TYPE=Release


IF NOT EXIST %BUILD_DIR% mkdir %BUILD_DIR%
cd %BUILD_DIR%
del /q CMakeCache.txt

echo cmake %SOURCE_DIR% -G "Visual Studio 9 2008" %VMIME_CONFIG%
cmake %SOURCE_DIR% -G "Visual Studio 9 2008" %VMIME_CONFIG%
exit /b %ERRORLEVEL%
